"""Add timestamp to feedback

Revision ID: 95d3b3eec8e1
Revises: f8bbced6258c
Create Date: 2024-09-28 08:25:43.390194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d3b3eec8e1'
down_revision = 'f8bbced6258c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=100),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
